### ISSUE TITLE
Error luego de cargar partida

### ISSUE THREAD

**Issue by dantepoblete** [dantepoblete/ScrabbleAR#2]
Luego de cargar la partida, en el transcurso de la partida(por lo general al tratar de validar la segunda palabra luego de cargar) ocurre el siguiente error:
![error](https://user-images.githubusercontent.com/62101433/88443377-76f68780-cdee-11ea-9a8f-ab29f830572f.jpg)

**Comment by tomibarbieri** [comment]
Excelente que ya lo pudieron resolver
